appName: Crop Health
APP:
  Name: Crop Health
  Logo: app_logo.png
  Location: Sudan
Client:
  Name: FGM International
  Logo: fgm.png
  Location: Sudan
  DataPath: ./clients/FGM.geojson
Us:
  Name: AmunData
  Logo: amundata_logo.png
  Location: Sudan
Sentinel:
  InstanceId: 456e94d0-903b-4abd-83a5-0d63d3869500     
  ClientId: da441cb3-4cc8-4d59-ad27-d20c26a5dc13 
  ClientSecret: wncMObciSrKd2iB2j6zc7bm2OIiN9yjf

StartDate : 2025-07-01
appSemanticVersion: 0.9.3
ClientName: FGM